/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./templates/**/*.html",
    "./static/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        // Catppuccin Latte (light theme)
        latte: {
          base: '#eff1f5',
          surface: '#e6e9ef',
          overlay: '#dce0e8',
          text: '#4c4f69',
          subtext: '#5c5f77',
          rosewater: '#dc8a78',
          flamingo: '#dd7878',
          pink: '#ea76cb',
          mauve: '#8839ef',
          red: '#d20f39',
          maroon: '#e64553',
          peach: '#fe640b',
          yellow: '#df8e1d',
          green: '#40a02b',
          teal: '#179299',
          sky: '#04a5e5',
          sapphire: '#209fb5',
          blue: '#1e66f5',
          lavender: '#7287fd',
        },
        // Catppuccin Frappé (dark theme)
        frappe: {
          base: '#303446',
          surface: '#414559',
          overlay: '#51576d',
          text: '#c6d0f5',
          subtext: '#a5adce',
          rosewater: '#f2d5cf',
          flamingo: '#eebebe',
          pink: '#f4b8e4',
          mauve: '#ca9ee6',
          red: '#e78284',
          maroon: '#ea999c',
          peach: '#ef9f76',
          yellow: '#e5c890',
          green: '#a6d189',
          teal: '#81c8be',
          sky: '#99d1db',
          sapphire: '#85c1dc',
          blue: '#8caaee',
          lavender: '#babbf1',
        },
        // Catppuccin Macchiato (dark theme)
        macchiato: {
          base: '#24273a',
          surface: '#363a4f',
          overlay: '#494d64',
          text: '#cad3f5',
          subtext: '#a5adcb',
          rosewater: '#f4dbd6',
          flamingo: '#f0c6c6',
          pink: '#f5bde6',
          mauve: '#c6a0f6',
          red: '#ed8796',
          maroon: '#ee99a0',
          peach: '#f5a97f',
          yellow: '#eed49f',
          green: '#a6da95',
          teal: '#8bd5ca',
          sky: '#91d7e3',
          sapphire: '#7dc4e4',
          blue: '#8aadf4',
          lavender: '#b7bdf8',
        },
        // Catppuccin Mocha (dark theme)
        mocha: {
          base: '#1e1e2e',
          surface: '#313244',
          overlay: '#45475a',
          text: '#cdd6f4',
          subtext: '#a6adc8',
          rosewater: '#f5e0dc',
          flamingo: '#f2cdcd',
          pink: '#f5c2e7',
          mauve: '#cba6f7',
          red: '#f38ba8',
          maroon: '#eba0ac',
          peach: '#fab387',
          yellow: '#f9e2af',
          green: '#a6e3a1',
          teal: '#94e2d5',
          sky: '#89dceb',
          sapphire: '#74c7ec',
          blue: '#89b4fa',
          lavender: '#b4befe',
        },
      },
    },
  },
  plugins: [],
}

